---
# IngressRoute для HTTP (редирект на HTTPS)
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: demo-app-http
  namespace: demo-app
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`serv.temasuug.ru`)
      kind: Rule
      services:
        - name: demo-app
          port: 80
      middlewares:
        - name: https-redirectscheme
---
# IngressRoute для HTTPS
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: demo-app-https
  namespace: demo-app
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`serv.temasuug.ru`)
      kind: Rule
      services:
        - name: demo-app
          port: 80
  tls:
    secretName: demo-app-tls
