{{- if and .Values.frontend.ingress.enabled .Values.certManager.enabled .Values.frontend.ingress.tls }}
{{- range .Values.frontend.ingress.tls }}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .secretName }}
  namespace: {{ $.Values.global.namespace }}
  labels:
    app.kubernetes.io/name: {{ include "notes-app.name" $ | quote }}
    app.kubernetes.io/instance: {{ $.Release.Name | quote }}
    app.kubernetes.io/managed-by: {{ $.Release.Service | quote }}
  annotations:
    "meta.helm.sh/release-namespace": "{{ $.Values.global.namespace }}"
    "meta.helm.sh/release-name": "{{ $.Release.Name }}"
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-weight: "10"
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
spec:
  secretName: {{ .secretName }}
  issuerRef:
    name: {{ $.Values.certManager.clusterIssuer.name }}
    kind: ClusterIssuer
  dnsNames:
    {{- range .hosts }}
    - {{ . | quote }}
    {{- end }}
{{- end }}
{{- end }}
