{{- if .Values.frontend.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "notes-app.fullname" . }}-ingress
  namespace: {{ .Values.global.namespace }}
  annotations:
    {{- range $key, $value := .Values.frontend.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
    "meta.helm.sh/release-namespace": "{{ .Values.global.namespace }}"
    "meta.helm.sh/release-name": "{{ .Release.Name }}"
    traefik.ingress.kubernetes.io/router.middlewares: "{{ .Values.global.namespace }}-security-headers@kubernetescrd,{{ .Values.global.namespace }}-redirectscheme@kubernetescrd"
spec:
  ingressClassName: {{ .Values.frontend.ingress.className }}
  tls:
    {{- range .Values.frontend.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  rules:
    {{- range .Values.frontend.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "notes-app.fullname" $ }}-frontend-svc
                port:
                  number: {{ $.Values.frontend.service.port }}
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: {{ include "notes-app.fullname" $ }}-backend-svc
                port:
                  number: {{ $.Values.backend.service.port }}
          - path: /docs
            pathType: Prefix
            backend:
              service:
                name: {{ include "notes-app.fullname" $ }}-backend-svc
                port:
                  number: {{ $.Values.backend.service.port }}
          - path: /redoc
            pathType: Prefix
            backend:
              service:
                name: {{ include "notes-app.fullname" $ }}-backend-svc
                port:
                  number: {{ $.Values.backend.service.port }}
    {{- end }}
{{- end }}