{{- if .Values.global.namespace }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.global.namespace | quote }}
  labels:
    name: {{ .Values.global.namespace | quote }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-20"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
{{- end }}