apiVersion: v1
kind: Secret
metadata:
 name: {{ include "notes-app.fullname" . }}-db-secret
 namespace: {{ .Values.global.namespace }}
type: Opaque
data:
 database_url: {{ printf "postgresql://postgres:%s@%s:5432/%s" .Values.postgresql.auth.postgresPassword .Values.postgresql.primary.service.name .Values.postgresql.auth.database | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
 name: {{ include "notes-app.fullname" . }}-app-secret
 namespace: {{ .Values.global.namespace }}
type: Opaque
data:
 secret_key: {{ .Values.backend.env.SECRET_KEY | b64enc | quote }}