apiVersion: v1
kind: Secret
metadata:
  name: {{ include "notes-app.fullname" . }}-db-secret
type: Opaque
data:
  database_url: {{ printf "postgresql://postgres:%s@%s:%s/%s" .Values.postgresql.auth.postgresPassword .Values.postgresql.primary.service.name .Values.postgresql.primary.service.ports.postgresql .Values.postgresql.auth.database | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "notes-app.fullname" . }}-app-secret
type: Opaque
data:
  secret_key: {{ .Values.backend.env.SECRET_KEY | b64enc | quote }}