{{- if .Values.frontend.ingress.enabled }}
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ .Values.global.namespace }}-security-headers
  namespace: {{ .Values.global.namespace }}
spec:
  headers:
    customResponseHeaders:
      Strict-Transport-Security: "max-age=31536000;includeSubDomains;preload"
      X-Frame-Options: "DENY"
      X-Content-Type-Options: "nosniff"
      Referrer-Policy: "strict-origin-when-cross-origin"
      X-XSS-Protection: "1; mode=block"
{{- end }}