{{- if and .Values.frontend.ingress.enabled .Values.traefik.tlsStoreEnabled -}}
apiVersion: traefik.io/v1alpha1
kind: TLSStore
metadata:
 name: default
 namespace: {{ .Values.global.namespace }}
spec:
  defaultCertificate:
    secretName: {{ (index .Values.frontend.ingress.tls 0).secretName }}
{{- end }}