{{- if and .Values.frontend.ingress.enabled .Values.traefik.tlsStoreEnabled -}}
apiVersion: traefik.containo.us/v1alpha1
kind: TLSStore
metadata:
 name: default
 namespace: {{ .Values.global.namespace }}
spec:
  defaultCertificate:
    secretName: notes-tls-cert
{{- end }}