apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: notes-app
data:
  POSTGRES_SERVER: "postgres-service"
  POSTGRES_USER: "postgres"
  POSTGRES_DB: "notes_app"
  API_V1_STR: "/api/v1"
  PROJECT_NAME: "Notes API"