---
# IngressRoute для Traefik
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: demo-app
  namespace: demo-app
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`serv.temasuug.ru`)
      kind: Rule
      services:
        - name: demo-app
          port: 80
