---
# IngressRoute для Traefik
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: demo-app
  namespace: demo-app
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`serv.temasuug.ru`)
      kind: Rule
      services:
        - name: demo-app
          port: 80
---
# IngressRoute для редиректа HTTP на HTTPS
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: demo-app-https-redirect
  namespace: demo-app
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`serv.temasuug.ru`)
      kind: Rule
      services:
        - name: demo-app
          port: 80
      middlewares:
        - name: https-redirectscheme
  tls:
    secretName: demo-app-tls
