apiVersion: v2
name: notes-app
description: Микросервисное приложение для управления заметками
type: application
version: 1.0.0
appVersion: "1.0"
dependencies:
  - name: postgresql
    version: 14.2
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled