apiVersion: v2
name: notes-app
description: Микросервисное приложение для управления заметками
type: application
version: 1.0.1
appVersion: "1.0"
dependencies:
 - name: postgresql
   version: 14.2.4
   repository: https://charts.bitnami.com/bitnami
   condition: postgresql.enabled
 - name: ingress-nginx
 - name: cert-manager
   version: v1.13.0
   repository: https://charts.jetstack.io
   condition: cert-manager.enabled