apiVersion: v2
name: notes-app
description: Микросервисное приложение для управления заметками
type: application
version: 1.0.1
appVersion: "1.0"
dependencies:
 - name: cert-manager
   version: v1.13.0
   repository: https://charts.jetstack.io
   condition: cert-manager.enabled
   import-values: []
 - name: postgresql
   version: 18.2.0
   repository: https://charts.bitnami.com/bitnami
   condition: postgresql.enabled